server:
  host: "0.0.0.0"
  port: 8080
  readTimeout: 60
  writeTimeout: 60
  maxHeaderBytes: 1048576

database:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  database: "test5bak"
  prefix: "aq3cms_"
  charset: "utf8mb4"
  maxIdle: 10
  maxOpen: 100

template:
  dir: "templets"
  cache: true
  defaultTpl: "default"

upload:
  savePath: "uploads"
  allowTypes:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  maxSize: 10485760
  waterMark: false
  waterMarkImg: "static/watermark.png"

log:
  path: "data/logs"
  level: "info"

cache:
  type: "memory"
  path: "data/cache"
  host: "localhost"
  port: 6379
  password: ""
  expire: 3600

site:
  name: "aq3cms"
  url: "http://localhost:8080"
  keywords: "aq3cms,CMS,内容管理系统"
  description: "aq3cms是一个基于Golang的内容管理系统"
  icp: ""
  statCode: ""
  copyRight: "Copyright © 2023 aq3cms. All Rights Reserved."
